export const OIL_LAYER = '//*[@data-qa="oil-Layer"]';
export const OIL_YES_BUTTON = '//*[@data-qa="oil-YesButton"]';
export const OIL_NO_BUTTON = '//*[@data-qa="oil-NotNowButton"]';
export const OIL_YES_SMALL_BUTTON = '//*[@data-qa="oil-small-YesButton"]';
export const HOST_SEND_OPTOUT_BUTTON = '//*[@data-qa="send-opt-out-button"]';
export const EVENT_NOTIFIER_DIV = '//*[@data-qa="event-notifier-div"]';
export const OIL_YES_POI_SMALL_BUTTON = '//*[@data-qa="oil-small-poi-YesButton"]';
export const OIL_YES_POI_BUTTON = '//*[@data-qa="oil-poi-YesButton"]';
export const PRIVACY_PAGE_URL = '//*[@data-qa="oil-privacy-page"]';
