export const OIL_LAYER = '//*[@data-qa="oil-Layer"]';
export const OIL_LAYER_FULL = '//*[@data-qa="oil-full"]';
export const OIL_LAYER_NOCOOKIES_ = '//*[@data-qa="oil-nocookies"]';
export const OIL_LAYER_POI_LIST = '//*[@data-qa="oil-poi-list"]';
export const OIL_LAYER_GROUP_LIST_ELEMENT = '.as-oil-poi-group-list-element:nth-of-type(1)';
export const OIL_LAYER_THIRD_PARTY_LIST_ELEMENT = '.as-oil-third-party-list-element';
export const OIL_BACK_BUTTON = '//*[@data-qa="oil-back-button"]';
export const OIL_YES_BUTTON = '//*[@data-qa="oil-YesButton"]';
export const OIL_CANCEL_BUTTON = '//*[@data-qa="oil-cancel-button"]';
export const OIL_PROCEED_BUTTON = '//*[@data-qa="oil-proceed-button"]';
export const OIL_SHOW_COMPANY_LIST_BUTTON = '.as-js-companyList';
export const OIL_SHOW_THIRD_PARTY_LIST_BUTTON = '.as-js-thirdPartyList';
export const HOST_SEND_OPTOUT_BUTTON = '//*[@data-qa="send-opt-out-button"]';
export const EVENT_NOTIFIER_DIV = '//*[@data-qa="event-notifier-div"]';
export const PRIVACY_PAGE_URL = '//*[@data-qa="oil-privacy-page"]';
export const OIL_ADVANCED_SETTINGS = '//*[@data-qa="oil-AdvancedSettingsButton"]';
export const OIL_ADVANCED_SETTINGS_WRAPPER = '//*[@data-qa="oil-cpc-overlay"]';
export const OIL_ADVANCED_SETTINGS_TEST_BUTTON_SHOW_PREF = '//*[@data-qa="show-pref-button"]';
export const OIL_ADVANCED_SETTINGS_TEST_BUTTON_TRIGGER_OPTIN = '//*[@data-qa="oil-YesButton"]';
export const OIL_ADVANCED_SETTINGS_SNIPPET = '//*[@data-qa="cpc-snippet"]';
// HINT: This does not work, as it is not clickable/hidden: export const OIL_DEFAULT_PURPOSE_SLIDER = '//*[@id="as-js-purpose-slider-1"]';
export const OIL_DEFAULT_PURPOSE_SLIDER = '//*[@id="as-js-purpose-slider-1"]/following-sibling::*[@class="as-oil-cpc__slider"]';
export const OIL_CUSTOM_PURPOSE_SLIDER = '//*[@id="as-js-purpose-slider-25"]';

export const OIL_CUTOM_VENDORS_HEADLINE = '//*[@id="as-oil-cpc-custom-third-parties"]';
export const OIL_CUTOM_VENDORS_LIST = '//*[@id="as-oil-custom-third-parties-list"]';

export const OIL_ADVANCED_SETTINGS_CUSTOM_PURPOSE_HEADER = '//*[@id="as-oil-cpc"]/div/div[3]/div[2]/div[7]/div/div[1]';
export const OIL_MANAGED_TAGS_SCRIPT_TAG = '//*[@id="managedScriptTag"]';
export const OIL_MANAGED_TAGS_IMG_TAG = '//*[@id="managedImgTag"]';
export const OIL_MANAGED_TAGS_DIV = '//*[@id="demoText"]';
export const PAGE_BACKGROUND = '.has-big-bad-background';
export const VENDOR_INTEGRATION_IFRAME_ID = 'vendor-integration-iframe';
export const VENDOR_INTEGRATION_IFRAME = `//*[@id="${VENDOR_INTEGRATION_IFRAME_ID}"]`;
export const GDPR_APPLY_BUTTON = '//*[@id="applyGDPR"]';
export const OIL_THIRD_PARTY_NAME = '.as-oil-third-party-name';
export const OIL_ADVANCED_SETTINGS_ACTIVE_PURPOSE_TAB = '.as-oil-tabs-cpc__purpose-label-active';
export const OIL_ADVANCED_SETTINGS_INACTIVE_PURPOSE_TABS = '.as-oil-tabs-cpc__purpose-labels > .as-oil-tabs-cpc__purpose-label-inactive:nth-child(4)';
export const IFRAME_PING_RESULT_SUCCESS = '//*[@id="ping-result-success"]';
export const IFRAME_PING_RESULT_VALUE = '//*[@id="ping-result-value"]';
export const IFRAME_GETCONSENTDATA_RESULT_SUCCESS = '//*[@id="getConsentData-result-success"]';
export const IFRAME_GETCONSENTDATA_RESULT_VALUE = '//*[@id="getConsentData-result-value"]';

export const OIL_OPTOUT_CONFIRM = '//*[@id="as-oil-optout-confirm"]';
