:project_root: ../../

[[section-design-decisions]]
== Design Decisions

=== Cross-Origin Messaging
****

The ``postMessage()`` method lifts this restriction by providing a way to securely pass messages across domains. The ``postMessage()`` method accepts two parameters.

*   ``message`` – A string or object that will be sent to the receiving window.
*   ``targetOrigin`` – The URL of the window that the message is being sent to. The protocol, port and hostname of the target window must match this parameter for the message to be sent. Specifying ``"*"`` will match any URL however this is strongly discouraged for security reasons.
This method should be called on the window that the message is being sent to. A reference to the target window can be obtained in a number of different ways:

*   When using ``window.open()`` a reference to the new window will be returned by the ``open()`` method.
*   For iframes you can access the ``contentWindow`` property on the desired iframe.

When a call to ``postMessage()`` is executed successfully a https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent[``MessageEvent``] will be fired on the receiving window. You can use a standard event listener to watch for this event and execute some code when it occurs.

The event passed into the listener callback has a property called ``data`` that can be used to access the string or object that was sent by ``postMessage()``.

So on the OIL hub side an event listener is added:

[source,javascript]
----
window.addEventListener('message', (e) => {
  let data = e.data;
include::{project_root}/src/scripts/iframe.listener.js[tags=hub-listener]
});
----

At the subscriber side the ``postMessage`` happenes to trigger an action on the hub:
[source,javascript]
----
include::{project_root}/src/scripts/poi.js[tags=subscriber-postMessage]
----

Now the subscriber can listen to messages from the hub:
[source,javascript]
----
window.addEventListener('message', (event) => {
include::{project_root}/src/scripts/poi.js[tags=subscriber-receiveMessage]
});
----

[options="header"]
|===
| ID         | Decision                                             | Date / Attendees
| OIL-DEC-1    | Tealium is responsible to not track by default.    | 12.04.2017 / Dr. Michael Sievers, Marcel Bankmann, Andreas Wagner, Michiel Slot, Martin Reinhardt
| OIL-DEC-2   | OIL is integrated as https://community.tealiumiq.com/t5/iQ-Tag-Management/JavaScript-Code-Extension/ta-p/11925[JavaScript Code Extension] in Tealium   | 12.04.2017 / Dr. Michael Sievers, Marcel Bankmann, Andreas Wagner, Michiel Slot, Martin Reinhardt
| OIL-DEC-3    | OIL is included within Tealium as Library for each business unit  | 12.04.2017 / Dr. Michael Sievers, Marcel Bankmann, Andreas Wagner, Michiel Slot, Martin Reinhardt
| OIL-DEC-4   | OIL sets one cookie which will be read by Tealium to optin tracking    | 12.04.2017 / Dr. Michael Sievers, Marcel Bankmann, Andreas Wagner, Michiel Slot, Martin Reinhardt
| OIL-DEC-5   | OIL Deployment is done manual via Tealium Web UI    | 12.04.2017 / Dr. Michael Sievers, Marcel Bankmann, Andreas Wagner, Michiel Slot, Martin Reinhardt
| OIL-DEC-6   | OIL uses postMessage with an iFrame to work without 3rd Party Cookies    | 19.04.2017 /  Marcel Bankmann, Andreas Wagner, Michiel Slot, Martin Reinhardt
|===
