== Version: {version}

== Introduction

=== About oil.js

The OIL project aims for a stable cross-company solution for the challenges the GDPR and new EU ePrivacy Regulation will pose to our business.

* Data privacy opt-in overlay for all users of services offered by various Axel Springer brands and/or units
* Local opt-in (called "Site Opt-In", SOI) as well as group-based cross-company opt-in (called "Power Opt-In", POI)
* Integration and hosting on Tealium with the option to run it standalone.

The Opt-In Layer (OIL) is an offical link:http://advertisingconsent.eu/iab-europe-transparency-consent-framework-list-of-registered-cmps/[Consent Management Provider (CMP)] after the IAB Europe "Transparency & Consent Framework".

=== Technical Quality Goals

* OIL will be held compatible with the latest official browser releases, going back to the latest version as listed below and tested on broad range of browsers using Browserstack.com:
** Chrome 14 - Latest
** IE 9 - Latest
** Firefox 9 - Latest
** Safari 6 - Latest
** Opera 12
** Apple iOS 5.1 - Latest
** Android 4.4.4 - Latest
* Continously integrated and delivered
* Modular and maintainable solution

=== Features

* Customisable UI and text with audit-proof versioning
* Fully configurable (cookie categories, timeouts, ...)
* Easy AB-Testing with extensive events for each user interaction
* AB-Tested in different brand specific designs with 250k unique users
* Supports IAB Europe Standard and additionally custom calls
* Supports Group-Opt-In
* Works with 99,9% of all browsers (in Germany) & Works with all devices and all resolutions
* Optimised for high performance and low latency (build to be loaded first)
* OpenSource
* Tested in the cloud on all possible devices
* Tealium integration and additional features via Tealium like reporting
* Redirect-Fallback for some older browsers and even for disabled 3rd party cookies in Safari
* High quality code with high test coverage and static code analysis
* Loads with low latency and asynchronously for different parts
* Happy path loads only 10.5k (subject to change and further optimization) of gzipped JavaScript
* Easy to implement with open documentation and examples, including dev kit
* With SaaS: Domain White Listing against unauthorized usage

=== Team & Stakeholders

[options="header",cols="1,2"]
|===
|Role/Name|Contact|
Business Owner | Johannes Fenner, CDP |
Legal Affairs | Susanne Stollhoff, Dr. Olaf Koglin |
Product Owner | Antonino Tumminelli, AS Ideas Engineering |
UX | Özden Gelgec, AS Ideas Engineering |
UX | Andreas Wagner, AS Ideas Engineering |
Developer | Sebastian Waschnick, AS Ideas Engineering |
Developer | Marcel Bankmann, AS Ideas Engineering |
Developer | Alexander Glintschert, AS Ideas Engineering |
Developer | Dmitri Awerkov-Schäfer, AS Ideas Engineering |
Tealium Consulting | Michael Sievers, CDP|
|===

=== Solution Strategy

According the proposal of the Commission, the European Parliament, and the Council of Ministers, websites will be required to prompt users with a menu of privacy options when they are visited for the first time.[1]

The Opt-In Layer (OIL) is our solution for these requirements consisting of three parts:

* A **subscriber** part, which adds the opt-in Layer to the host pages DOM and asks the user to opt-in.
* A **hub** part, which acts as a registry site for POI on a domain hosted by Ideas Engineering. This is optional and only needed for POI functionality.
* A **backend** part on a domain hosted by Ideas Engineering that provides all the texts and labels shown by the Opt-In Layer. Different languages and variants of these texts and labels are supported.

Opt-In Information is stored in a first party cookie in the user's browser and communicated in a general way to the host site and Tealium. For Power Opt-In there is also a 3rd party cookie stored on a second domain to share information between sites.

=== Why is there no native app support?

Native mobile apps are very customized concerning technology stack and implementation of tracking and advertising. Therefore, the OIL project won't offer a generic solution for this purpose.
Each unit has to review their app how tracking and advertising is implemented and find a solution to get the consent from the user by a dialog.
Consents both on desktop or mobile browsers given by the user are not able to be used in the mobile app because:
* mobile browsers and in app web views use different ressources to store their cookies
* desktop browsers and mobile apps have no physical connections
