== Version: {version}

== Introduction

=== About oil.js

The OIL project aims for a stable cross-company solution for the challenges the GDPR and new EU ePrivacy Regulation will pose to our business.

* Data privacy opt-in overlay for all users of services offered by various Axel Springer brands and/or units
* Local opt-in (called "Site Opt-In", SOI) as well as group-based cross-company opt-in (called "Power Opt-In", POI)
* Integration and hosting on Tealium with the option to run it standalone.

=== Technical Quality Goals

* OIL will be held compatible with the latest official browser releases, going back to the latest version as listed below and tested on broad range of browsers using Browserstack.com:
** Chrome 14 - Latest
** IE 9 - Latest
** Firefox 9 - Latest
** Safari 6 - Latest
** Opera 12
** Apple iOS 5.1 - Latest
** Android 4.4.4 - Latest
* Continously integrated and delivered
* Modular and maintainable solution

=== Team & Stakeholders

[options="header",cols="1,2"]
|===
|Role/Name|Contact|
Business Owner | Johannes Fenner, CDP |
Legal Affairs | Susanne Stollhoff, Dr. Olaf Koch |
Product Owner | Antonino Tumminelli, AS Ideas Engineering |
UX | Özden Gelgec, AS Ideas Engineering |
UX | Andreas Wagner, AS Ideas Engineering |
Developer | Sebastian Waschnick, AS Ideas Engineering |
Developer | Marcel Bankmann, AS Ideas Engineering |
Tealium | Michael Sievers, CDP|
|===

=== Solution Strategy

According the proposal of the Commission, the European Parliament, and the Council of Ministers, websites will be required to prompt users with a menu of privacy options when they are visited for the first time.[1]

The Opt-In Layer (OIL) is our solution for these requirements consisting of two parts:

* A **subscriber** part, which adds the opt-in Layer to the host pages DOM and asks the user to opt-in.
* A **hub** part, which acts as a registry site for POI on a domain hosted by Ideas Engineering. This is optional and only needed for POI functionality.

Opt-In Information is stored in a first party cookie in the users browser and communicated in a general way to the host site and Tealium. For Power-Opt-In there is also a 3rd party cookie stored on a second domain to share information between sites. The OIL Layer currently does not have a central database.

=== Why is there no native app support?

Native mobile apps are very customized concerning technology stack and implementation of tracking and advertising. Therefore, the OIL project won't offer a generic solution for this purpose.
Each unit has to review their app how tracking and advertising is implemented and find a solution to get the consent from the user by a dialog.
Consents both on desktop or mobile browsers given by the user are not able to be used in the mobile app because:
* mobile browsers and in app web views use different ressources to store their cookies
* desktop browsers and mobile apps have no physical connections
