== Quickstart

=== How to implement OIL on your site

Basic implementation requires two steps:

* Include oil.js sources on your site
* Add your own oil.js configuration snippet to your html

Optionally you can:

* <<styling-guide,Style>> your layer according to your style guide.
* Create your own <<texts-locale-object,language pack>>.

=== Including oil.js sources on your site

* <<Self-hosted solution>>
* <<Delivery through the unpkg.com cdn>>
* <<Delivery through Tealium>>

==== Self-hosted solution

This is the recommended way to get OIL to work on your site. Upload all the files of the latest release to your own server and set your configuration to use that server.

You can download all the files for a release from https://oil.axelspringer.com/release. Upload a release folders contents to your server and continute with <<Integrate OIL>>.

==== Delivery through the unpkg.com cdn

If you don't have your own server available and/or don't want to use the POI features, it may be enough to just include the OIL sources from the `unpkg.ocm` CDN. Example:


==== Delivery through Tealium

An alternative way to integrate OIL with your page is the use of a tag manager like Tealium. If you prefer this solution please read section <<OIL and Tealium>>.

OIL creates a standard for the Opt-In but can't automatically stop your site from tracking your users. So to actually make your page respond to opt-ins you also need to do the following:

* Make sure your page doesn't track the user in its default state.
* If possible, use Tealium for all tracking activities and take advantage of the loading rules support that OIL provides (see section <<OIL and Tealium>> for details).
* Listen to OIL events for loading non-Tealium tags, after the user opted in.
* Use the <<Soft Blocking of DOM Elements,soft-blocking feature>> for tags that OIL provides.

==== Release files

For reference: these are the files that belong to a release.

* `oil.{version}.min.js` - This is the file you will need to reference in your website - see below.
* `hub.{version}.min.js` - This is the file you will need for the power opt-in feature. See sections <<POI – Power Opt-In>> for details.
* `hub.html` - This is the file you will need for the power opt-in feature.
* `poi-lists` - A directory that is needed for the power opt-in feature. It contains JSON files defining POI groups. See sections <<POI – Power Opt-In>> and <<POI-List>> for details.
* Chunks, beginning with numbers - they will be loaded asynchronously and you don't need to do anything with them.
** `0.{version}.chunk.js`
** `X.{version}.chunk.js`
* `oildevkit.{version}.min.js` - This is the file you will need to use the small OIL SDK. See section <<OIL SDK>> for details.

The version number is part of `.js` files because updated versions of the scripts will be released using a different filename hence we'll never alter an existing version.



=== Integrate OIL

To integrate your self-hosted OIL with your website, add the following code snippets to your html:
[source, html, subs="attributes"]
----
&lt;script>
include::../../../dist/oilstub.{version}.min.js[]
&lt;/script>
----

==== Self-hosted solution

For a self-hosted release, load the javascript from your site:

[source,html,subs="attributes"]
----
&lt;script src="https://&lt;your-host&gt;/&lt;path-to-oil&gt;/oil.{version}.min.js" type="text/javascript">&lt;/script>
----

==== Delivery through unpkg.com

[source,html,subs="attributes"]
----
&lt;script src="//unpkg.com/@ideasio/oil.js/dist/latest/oil.min.js" type="text/javascript"&gt;&lt;/script>
----

Please make sure you're working with the *latest version* available. Check https://oil.axelspringer.com/release or  further updates. Choose the latest version or the version fitting to this documentation.


=== Configure OIL

To ensure that your self-hosted OIL can find all its necessary scripts you must define the `publicPath` parameter in your <<configuring-oil,oil configuration>>.
It specifies the server path from which all chunks and ressources will be loaded. This is a minimal configuration tag:

[source,html,subs="attributes"]
----
&lt;script id="oil-configuration" type="application/configuration"&gt;
  {
    "publicPath": "//&lt;your-host&gt;/&lt;path-to-oil&gt;",
    "locale_url": "//&lt;your-host&gt;/&lt;path-to-locale&gt;/myLocale.json"
  }
&lt;/script&gt;
----


==== Delivery through unpkg.com

Note that you will have to add your own locale to the configuration block. See <<Texts & Locale Object>> section for details.

[source,html,subs="attributes"]
----
&lt;script id="oil-configuration" type="application/configuration"&gt;
  {
    "publicPath": "//unpkg.com/@ideasio/oil.js/dist/latest/",
    "locale": { localeId: "myLocale", version: "1", texts: {"label_intro_heading":"I am a stub" }}
  }
&lt;/script&gt;
----

include::02-quickstart/dev-kit.adoc[]
