== Quickstart

=== How to implement OIL on your site

Setting up OIL on your page consists of the following steps:

* <<Install OIL>> on a host of your site.
* <<Integrate OIL,Add the oil.js javascript snippet>> to your page.
* <<Configure OIL,Add a configuration>> block to your pages DOM.
* <<styling-guide,Style>> your layer according to your style guide.
* Create your own <<texts-locale-object,language pack>>.

OIL creates a standard for the Opt-In but can't automatically stop your site from tracking your users. So to actually make your page respond to opt-ins you also need to do the following:

* Make sure your page doesn't track the user in its default state.
* If possible, use Tealium for all tracking activities and use the loading rules we provide.
* Listen to OIL events for loading non-Tealium tags, after the user opted in.
* Use the <<Soft Blocking of DOM Elements,soft-blocking feature>> for tags that OIL provides.

==== Install OIL

To add OIL to your site, at first you need an OIL installation. You can download it from https://oil.axelspringer.com/release. The following files must be located on a host of your site:

* `oil.{version}.min.js` - This is the file you will need to reference in your website - see below.
* `hub.{version}.min.js` - This is the file you will need for the power opt-in feature. See sections <<POI – Power Opt-In>> for details.
* `hub.html` - This is the file you will need for the power opt-in feature.
* `poi-lists` - A directory that is needed for the power opt-in feature. It contains JSON files defining POI groups. See sections <<POI – Power Opt-In>> and <<POI-List>> for details.
* Chunks, beginning with numbers - they will be loaded asynchronously and you don't need to do anything with them.
** `0.{version}.chunk.js`
** `X.{version}.chunk.js`
* `oildevkit.{version}.min.js` - This is the file you will need to use the small OIL SDK. See section <<OIL SDK>> for details.

The version number is part of `.js` files because updated versions of the scripts will be released using a different filename hence we'll never alter an existing version.

==== Integrate OIL

To integrate your self-hosted OIL with your website, add the following code:
[source, html, subs="attributes"]
----
&lt;script>
include::../../../dist/oilstub.{version}.min.js[]
&lt;/script>
&lt;script type="text/javascript" src="https://&lt;your-host&gt;/&lt;path-to-oil&gt;/oil.{version}.min.js">&lt;/script>
----

Please make sure you're working with the *latest version* available. Please check https://oil.axelspringer.com/release for further updates. Choose the latest version or the version fitting to this documentation.

==== Configure OIL

To ensure that your self-hosted OIL can find all its necessary scripts you must define the `publicPath` parameter in your <<configuring-oil,oil configuration>>.
It specifies the server path from which all chunks and ressources will be loaded. This is a minimal configuration tag:

[source,json,subs="attributes"]
----
<script id="oil-configuration" type="application/configuration">
  {
    "publicPath": "//&lt;your-host&gt;/&lt;path-to-oil&gt;",
    "locale_url": "//&lt;your-host&gt;/&lt;path-to-locale&gt;myLocale.json"
  }
</script>
----

include::02-quickstart/dev-kit.adoc[]
