== Development

=== Quick Links
Jira: https://id-jira.axelspringer.de/browse/OIL

Jenkins: https://kube-jenkins.ipool.asideas.de/view/OIL%20Project/

Overview: http://oil.axelspringer.com

=== OIL SDK

This is a like a drop-in to add a small sdk to any site, which has oil included.

Add this to your favorites and open the link on the website you want it to be included:

[source,javascript]
----

----

=== Hub Deployment
To deploy the hub you need to deploy the project with an index.html loading the hub.[version].min.js

For compatibility with Internet Explorer 9+ you need to add the following header to the server response to allow 3rd party cookies for POI.

[source,json]
----
include::../../../etc/headerConfig.js[tags=p3p-config]
----

include::development/tealium-deployment.adoc[]

include::development/locale-configuration.adoc[]

include::development/unofficial-configuration.adoc[]

=== FYI: Cross-Origin Messaging

The ``postMessage()`` method lifts this restriction by providing a way to securely pass messages across domains. The ``postMessage()`` method accepts two parameters.

****
*   ``message`` – A string or object that will be sent to the receiving window.
*   ``targetOrigin`` – The URL of the window that the message is being sent to. The protocol, port and hostname of the target window must match this parameter for the message to be sent. Specifying ``"*"`` will match any URL however this is strongly discouraged for security reasons.
This method should be called on the window that the message is being sent to. A reference to the target window can be obtained in a number of different ways:

*   When using ``window.open()`` a reference to the new window will be returned by the ``open()`` method.
*   For iframes you can access the ``contentWindow`` property on the desired iframe.
****
When a call to ``postMessage()`` is executed successfully a https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent[``MessageEvent``] will be fired on the receiving window. You can use a standard event listener to watch for this event and execute some code when it occurs.

The event passed into the listener callback has a property called ``data`` that can be used to access the string or object that was sent by ``postMessage()``.

So on the OIL hub side an event listener is added:

[source,javascript]
----
window.addEventListener('message', (e) => {
  let data = e.data;
include::../../../src/scripts/hub/hub_oil.js[tags=hub-listener]
});
----

At the subscriber side the ``postMessage`` happens to trigger an action on the hub:
[source,javascript]
----
include::../../../src/scripts/core/core_poi.js[tags=subscriber-postMessage]
----

Now the subscriber can listen to messages from the hub:
[source,javascript]
----
window.addEventListener('message', (event) => {
include::../../../src/scripts/core/core_poi.js[tags=subscriber-receiveMessage]
});
----
