export const OIL_LABELS = {
  ATTR_LABEL_INTRO_HEADING: 'label_intro_heading',
  ATTR_LABEL_INTRO: 'label_intro',
  ATTR_LABEL_INTRO_START: 'label_intro_start',
  ATTR_LABEL_INTRO_END: 'label_intro_end',
  ATTR_LABEL_BUTTON_YES: 'label_button_yes',
  ATTR_LABEL_BUTTON_BACK: 'label_button_back',
  ATTR_LABEL_BUTTON_PRIVACY: 'label_button_privacy',
  ATTR_LABEL_BUTTON_ADVANCED_SETTINGS: 'label_button_advanced_settings',
  ATTR_LABEL_POI_GROUP_LIST_HEADING: 'label_poi_group_list_heading',
  ATTR_LABEL_POI_GROUP_LIST_TEXT: 'label_poi_group_list_text',
  ATTR_LABEL_THIRD_PARTY_LIST_HEADING: 'label_thirdparty_list_heading',
  ATTR_LABEL_THIRD_PARTY_LIST_TEXT: 'label_thirdparty_list_text',

  ATTR_LABEL_CPC_HEADING: 'label_cpc_heading',
  ATTR_LABEL_CPC_TEXT: 'label_cpc_text',
  ATTR_LABEL_CPC_01_TEXT: 'label_cpc_purpose_01_text',
  ATTR_LABEL_CPC_01_DESC: 'label_cpc_purpose_01_desc',
  ATTR_LABEL_CPC_02_TEXT: 'label_cpc_purpose_02_text',
  ATTR_LABEL_CPC_02_DESC: 'label_cpc_purpose_02_desc',
  ATTR_LABEL_CPC_03_TEXT: 'label_cpc_purpose_03_text',
  ATTR_LABEL_CPC_03_DESC: 'label_cpc_purpose_03_desc',
  ATTR_LABEL_CPC_04_TEXT: 'label_cpc_purpose_04_text',
  ATTR_LABEL_CPC_04_DESC: 'label_cpc_purpose_04_desc',
  ATTR_LABEL_CPC_05_TEXT: 'label_cpc_purpose_05_text',
  ATTR_LABEL_CPC_05_DESC: 'label_cpc_purpose_05_desc',
  ATTR_LABEL_CPC_06_TEXT: 'label_cpc_purpose_06_text',
  ATTR_LABEL_CPC_06_DESC: 'label_cpc_purpose_06_desc',
  ATTR_LABEL_CPC_07_TEXT: 'label_cpc_purpose_07_text',
  ATTR_LABEL_CPC_07_DESC: 'label_cpc_purpose_07_desc',

  ATTR_LABEL_NO_COOKIES_HEADING: 'label_nocookie_head',
  ATTR_LABEL_NO_COOKIES_TEXT: 'label_nocookie_text'
};

