export const OIL_LABELS = {
  ATTR_LABEL_INTRO_HEADING: 'label_intro_heading',
  ATTR_LABEL_INTRO: 'label_intro',
  ATTR_LABEL_INTRO_START: 'label_intro_start',
  ATTR_LABEL_INTRO_END: 'label_intro_end',
  ATTR_LABEL_BUTTON_YES: 'label_button_yes',
  ATTR_LABEL_BUTTON_BACK: 'label_button_back',
  ATTR_LABEL_BUTTON_PRIVACY: 'label_button_privacy',
  ATTR_LABEL_BUTTON_ADVANCED_SETTINGS: 'label_button_advanced_settings',
  ATTR_LABEL_ADVANCED_SETTINGS_HEADING: 'label_advanced_settings_heading',
  ATTR_LABEL_ADVANCED_SETTINGS_TEXT: 'label_advanced_settings_text',
  ATTR_LABEL_POI_GROUP_LIST_HEADING: 'label_poi_group_list_heading',
  ATTR_LABEL_POI_GROUP_LIST_TEXT: 'label_poi_group_list_text',
  ATTR_LABEL_THIRD_PARTY_LIST_HEADING: 'label_thirdparty_list_heading',
  ATTR_LABEL_THIRD_PARTY_LIST_TEXT: 'label_thirdparty_list_text',
  ATTR_LABEL_ADVANCED_SETTINGS_ESSENTIAL_TEXT: 'label_advanced_settings_essential_text',
  ATTR_LABEL_ADVANCED_SETTINGS_ESSENTIAL_VERBOSE: 'label_advanced_settings_essential_verbose',
  ATTR_LABEL_ADVANCED_SETTINGS_FUNCTIONAL_TEXT: 'label_advanced_settings_functional_text',
  ATTR_LABEL_ADVANCED_SETTINGS_FUNCTIONAL_VERBOSE: 'label_advanced_settings_functional_verbose',
  ATTR_LABEL_ADVANCED_SETTINGS_ADVERTISING_TEXT: 'label_advanced_settings_advertising_text',
  ATTR_LABEL_ADVANCED_SETTINGS_ADVERTISING_VERBOSE: 'label_advanced_settings_advertising_verbose',
  ATTR_LABEL_NO_COOKIES_HEADING: 'label_nocookie_head',
  ATTR_LABEL_NO_COOKIES_TEXT: 'label_nocookie_text'
};

